#!/bin/bash
echo "The name of the script is $0"
echo "The first argument is $1"
echo "The second argument is $2"
echo "The third argument is $3"
echo "The total number of arguments are $#"
echo "The arguments are $@"
echo "The arguments are $*"
echo "process id is $$"
echo "status of the command $?"
